import type { Delivery, Driver, Vehicle, Route, KPIs, Occurrence } from './types';

// Mock Drivers
export const mockDrivers: Driver[] = [
  {
    id: 'd1',
    cpf: '123.456.789-00',
    nome: 'Carlos Silva',
    cnh: '12345678900',
    cnh_validade: new Date('2025-12-31'),
    telefone: '(11) 99999-1111',
    email: 'carlos@logitrack.com',
    foto_url: '/avatars/carlos.jpg',
    veiculo_id: 'v1',
    status: 'EM_ROTA',
    localizacao_atual: { latitude: -23.5505, longitude: -46.6333, timestamp: new Date() },
    created_at: new Date(),
    updated_at: new Date(),
    ativo: true,
  },
  {
    id: 'd2',
    cpf: '234.567.890-11',
    nome: 'Ana Oliveira',
    cnh: '23456789011',
    cnh_validade: new Date('2026-06-15'),
    telefone: '(11) 99999-2222',
    email: 'ana@logitrack.com',
    veiculo_id: 'v2',
    status: 'EM_ROTA',
    localizacao_atual: { latitude: -23.5629, longitude: -46.6544, timestamp: new Date() },
    created_at: new Date(),
    updated_at: new Date(),
    ativo: true,
  },
  {
    id: 'd3',
    cpf: '345.678.901-22',
    nome: 'Pedro Santos',
    cnh: '34567890122',
    cnh_validade: new Date('2024-10-20'),
    telefone: '(11) 99999-3333',
    email: 'pedro@logitrack.com',
    veiculo_id: 'v3',
    status: 'DISPONIVEL',
    created_at: new Date(),
    updated_at: new Date(),
    ativo: true,
  },
  {
    id: 'd4',
    cpf: '456.789.012-33',
    nome: 'Maria Costa',
    cnh: '45678901233',
    cnh_validade: new Date('2025-08-10'),
    telefone: '(11) 99999-4444',
    email: 'maria@logitrack.com',
    veiculo_id: 'v4',
    status: 'EM_ROTA',
    localizacao_atual: { latitude: -23.5489, longitude: -46.6388, timestamp: new Date() },
    created_at: new Date(),
    updated_at: new Date(),
    ativo: true,
  },
];

// Mock Vehicles
export const mockVehicles: Vehicle[] = [
  {
    id: 'v1',
    placa: 'ABC-1234',
    tipo: 'VAN',
    modelo: 'Fiat Ducato',
    ano: 2022,
    capacidade_kg: 1500,
    capacidade_m3: 12,
    km_atual: 45230,
    consumo_medio: 9.5,
    status: 'EM_USO',
    motorista_id: 'd1',
    localizacao_atual: { latitude: -23.5505, longitude: -46.6333, timestamp: new Date() },
    created_at: new Date(),
    updated_at: new Date(),
    ativo: true,
  },
  {
    id: 'v2',
    placa: 'DEF-5678',
    tipo: 'FIORINO',
    modelo: 'Fiat Fiorino',
    ano: 2023,
    capacidade_kg: 650,
    capacidade_m3: 4,
    km_atual: 23100,
    consumo_medio: 12,
    status: 'EM_USO',
    motorista_id: 'd2',
    localizacao_atual: { latitude: -23.5629, longitude: -46.6544, timestamp: new Date() },
    created_at: new Date(),
    updated_at: new Date(),
    ativo: true,
  },
  {
    id: 'v3',
    placa: 'GHI-9012',
    tipo: 'TRUCK',
    modelo: 'VW Delivery',
    ano: 2021,
    capacidade_kg: 8000,
    capacidade_m3: 40,
    km_atual: 89500,
    consumo_medio: 4.5,
    status: 'DISPONIVEL',
    created_at: new Date(),
    updated_at: new Date(),
    ativo: true,
  },
  {
    id: 'v4',
    placa: 'JKL-3456',
    tipo: 'MOTO',
    modelo: 'Honda CG 160',
    ano: 2023,
    capacidade_kg: 30,
    capacidade_m3: 0.1,
    km_atual: 12300,
    consumo_medio: 35,
    status: 'EM_USO',
    motorista_id: 'd4',
    localizacao_atual: { latitude: -23.5489, longitude: -46.6388, timestamp: new Date() },
    created_at: new Date(),
    updated_at: new Date(),
    ativo: true,
  },
];

// Mock Deliveries
export const mockDeliveries: Delivery[] = [
  {
    id: 'e1',
    codigo_rastreio: 'LT2024001',
    pedido_id: 'PED-001',
    rota_id: 'r1',
    remetente: {
      nome: 'Tech Store LTDA',
      documento: '12.345.678/0001-90',
      endereco: {
        logradouro: 'Av. Paulista',
        numero: '1000',
        bairro: 'Bela Vista',
        cidade: 'Sao Paulo',
        uf: 'SP',
        cep: '01310-100',
      },
      contato: '(11) 3333-1111',
    },
    destinatario: {
      nome: 'Joao Pereira',
      documento: '987.654.321-00',
      endereco: {
        logradouro: 'Rua Augusta',
        numero: '500',
        complemento: 'Apto 42',
        bairro: 'Consolacao',
        cidade: 'Sao Paulo',
        uf: 'SP',
        cep: '01304-000',
        latitude: -23.5545,
        longitude: -46.6592,
      },
      contato: '(11) 99888-1234',
    },
    volumes: 2,
    peso_kg: 5.5,
    cubagem_m3: 0.08,
    valor_declarado: 2500,
    nota_fiscal: 'NF-123456',
    status: 'EM_TRANSITO',
    prazo_entrega: new Date(Date.now() + 2 * 60 * 60 * 1000),
    data_coleta: new Date(Date.now() - 3 * 60 * 60 * 1000),
    tentativas: 0,
    historico: [
      {
        id: 'h1',
        entrega_id: 'e1',
        status: 'PENDENTE',
        descricao: 'Pedido cadastrado no sistema',
        usuario_id: 'sys',
        created_at: new Date(Date.now() - 24 * 60 * 60 * 1000),
      },
      {
        id: 'h2',
        entrega_id: 'e1',
        status: 'COLETADO',
        descricao: 'Mercadoria coletada',
        usuario_id: 'd1',
        created_at: new Date(Date.now() - 3 * 60 * 60 * 1000),
      },
      {
        id: 'h3',
        entrega_id: 'e1',
        status: 'EM_TRANSITO',
        descricao: 'Em rota de entrega',
        usuario_id: 'd1',
        created_at: new Date(Date.now() - 1 * 60 * 60 * 1000),
      },
    ],
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 'e2',
    codigo_rastreio: 'LT2024002',
    pedido_id: 'PED-002',
    rota_id: 'r1',
    remetente: {
      nome: 'Fashion Shop',
      documento: '23.456.789/0001-01',
      endereco: {
        logradouro: 'Rua Oscar Freire',
        numero: '200',
        bairro: 'Jardins',
        cidade: 'Sao Paulo',
        uf: 'SP',
        cep: '01426-000',
      },
      contato: '(11) 3333-2222',
    },
    destinatario: {
      nome: 'Maria Fernanda',
      documento: '876.543.210-99',
      endereco: {
        logradouro: 'Av. Brasil',
        numero: '1500',
        bairro: 'Jardim America',
        cidade: 'Sao Paulo',
        uf: 'SP',
        cep: '01430-000',
        latitude: -23.5678,
        longitude: -46.6789,
      },
      contato: '(11) 99777-5678',
    },
    volumes: 1,
    peso_kg: 0.8,
    cubagem_m3: 0.02,
    valor_declarado: 450,
    nota_fiscal: 'NF-123457',
    status: 'ENTREGUE',
    prazo_entrega: new Date(Date.now() - 1 * 60 * 60 * 1000),
    data_coleta: new Date(Date.now() - 5 * 60 * 60 * 1000),
    data_entrega: new Date(Date.now() - 30 * 60 * 1000),
    assinatura_url: '/signatures/sig-e2.png',
    foto_canhoto_url: '/canhotos/canhoto-e2.jpg',
    recebedor_nome: 'Maria Fernanda',
    recebedor_documento: '876.543.210-99',
    tentativas: 1,
    historico: [],
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 'e3',
    codigo_rastreio: 'LT2024003',
    pedido_id: 'PED-003',
    rota_id: 'r2',
    remetente: {
      nome: 'Eletro Plus',
      documento: '34.567.890/0001-12',
      endereco: {
        logradouro: 'Av. Reboucas',
        numero: '3000',
        bairro: 'Pinheiros',
        cidade: 'Sao Paulo',
        uf: 'SP',
        cep: '05401-300',
      },
      contato: '(11) 3333-3333',
    },
    destinatario: {
      nome: 'Roberto Almeida',
      documento: '765.432.109-88',
      endereco: {
        logradouro: 'Rua dos Pinheiros',
        numero: '800',
        bairro: 'Pinheiros',
        cidade: 'Sao Paulo',
        uf: 'SP',
        cep: '05422-001',
        latitude: -23.5612,
        longitude: -46.6922,
      },
      contato: '(11) 99666-9012',
    },
    volumes: 3,
    peso_kg: 25,
    cubagem_m3: 0.5,
    valor_declarado: 3200,
    nota_fiscal: 'NF-123458',
    status: 'INSUCESSO',
    prazo_entrega: new Date(Date.now() - 2 * 60 * 60 * 1000),
    data_coleta: new Date(Date.now() - 6 * 60 * 60 * 1000),
    motivo_insucesso: 'Destinatario ausente',
    tentativas: 1,
    historico: [],
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 'e4',
    codigo_rastreio: 'LT2024004',
    pedido_id: 'PED-004',
    rota_id: 'r1',
    remetente: {
      nome: 'Livros & Cia',
      documento: '45.678.901/0001-23',
      endereco: {
        logradouro: 'Rua da Consolacao',
        numero: '1500',
        bairro: 'Consolacao',
        cidade: 'Sao Paulo',
        uf: 'SP',
        cep: '01301-100',
      },
      contato: '(11) 3333-4444',
    },
    destinatario: {
      nome: 'Lucia Martins',
      documento: '654.321.098-77',
      endereco: {
        logradouro: 'Al. Santos',
        numero: '1200',
        complemento: 'Sala 501',
        bairro: 'Cerqueira Cesar',
        cidade: 'Sao Paulo',
        uf: 'SP',
        cep: '01419-002',
        latitude: -23.5590,
        longitude: -46.6611,
      },
      contato: '(11) 99555-3456',
    },
    volumes: 1,
    peso_kg: 2.3,
    cubagem_m3: 0.03,
    valor_declarado: 180,
    nota_fiscal: 'NF-123459',
    status: 'PENDENTE',
    prazo_entrega: new Date(Date.now() + 4 * 60 * 60 * 1000),
    tentativas: 0,
    historico: [],
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 'e5',
    codigo_rastreio: 'LT2024005',
    pedido_id: 'PED-005',
    rota_id: 'r2',
    remetente: {
      nome: 'Pharma Express',
      documento: '56.789.012/0001-34',
      endereco: {
        logradouro: 'Av. Faria Lima',
        numero: '2000',
        bairro: 'Itaim Bibi',
        cidade: 'Sao Paulo',
        uf: 'SP',
        cep: '04538-132',
      },
      contato: '(11) 3333-5555',
    },
    destinatario: {
      nome: 'Clinica Vida',
      documento: '67.890.123/0001-45',
      endereco: {
        logradouro: 'Rua Funchal',
        numero: '400',
        bairro: 'Vila Olimpia',
        cidade: 'Sao Paulo',
        uf: 'SP',
        cep: '04551-060',
        latitude: -23.5945,
        longitude: -46.6833,
      },
      contato: '(11) 99444-7890',
    },
    volumes: 5,
    peso_kg: 8,
    cubagem_m3: 0.15,
    valor_declarado: 5600,
    nota_fiscal: 'NF-123460',
    status: 'EM_TRANSITO',
    prazo_entrega: new Date(Date.now() + 1 * 60 * 60 * 1000),
    data_coleta: new Date(Date.now() - 2 * 60 * 60 * 1000),
    tentativas: 0,
    historico: [],
    created_at: new Date(),
    updated_at: new Date(),
  },
];

// Mock Routes
export const mockRoutes: Route[] = [
  {
    id: 'r1',
    codigo: 'ROTA-001',
    data_prevista: new Date(),
    motorista_id: 'd1',
    veiculo_id: 'v1',
    entregas: mockDeliveries.filter(d => d.rota_id === 'r1'),
    status: 'EM_ANDAMENTO',
    km_total: 45,
    km_percorrido: 28,
    tempo_estimado_min: 180,
    sequencia_otimizada: ['e4', 'e1', 'e2'],
    created_at: new Date(),
    updated_at: new Date(),
    iniciada_em: new Date(Date.now() - 3 * 60 * 60 * 1000),
  },
  {
    id: 'r2',
    codigo: 'ROTA-002',
    data_prevista: new Date(),
    motorista_id: 'd2',
    veiculo_id: 'v2',
    entregas: mockDeliveries.filter(d => d.rota_id === 'r2'),
    status: 'EM_ANDAMENTO',
    km_total: 32,
    km_percorrido: 15,
    tempo_estimado_min: 120,
    sequencia_otimizada: ['e3', 'e5'],
    created_at: new Date(),
    updated_at: new Date(),
    iniciada_em: new Date(Date.now() - 2 * 60 * 60 * 1000),
  },
];

// Mock Occurrences
export const mockOccurrences: Occurrence[] = [
  {
    id: 'o1',
    tipo: 'ATRASO',
    descricao: 'Transito intenso na Marginal Pinheiros',
    rota_id: 'r1',
    motorista_id: 'd1',
    gravidade: 'MEDIA',
    status: 'ABERTA',
    created_at: new Date(Date.now() - 30 * 60 * 1000),
  },
  {
    id: 'o2',
    tipo: 'AVARIA',
    descricao: 'Embalagem danificada - produto intacto',
    entrega_id: 'e3',
    gravidade: 'BAIXA',
    status: 'EM_ANALISE',
    created_at: new Date(Date.now() - 1 * 60 * 60 * 1000),
  },
];

// Mock KPIs
export const mockKPIs: KPIs = {
  otif: 87.5,
  lead_time_medio: 4.2,
  custo_por_km: 2.85,
  taxa_insucesso: 8.3,
  entregas_dia: 156,
  km_dia: 1245,
};

// Chart data for delivery trends
export const deliveryTrendData = [
  { hora: '06:00', entregas: 5, insucesso: 0 },
  { hora: '07:00', entregas: 12, insucesso: 1 },
  { hora: '08:00', entregas: 28, insucesso: 2 },
  { hora: '09:00', entregas: 35, insucesso: 3 },
  { hora: '10:00', entregas: 42, insucesso: 2 },
  { hora: '11:00', entregas: 38, insucesso: 4 },
  { hora: '12:00', entregas: 15, insucesso: 1 },
  { hora: '13:00', entregas: 22, insucesso: 2 },
  { hora: '14:00', entregas: 45, insucesso: 3 },
  { hora: '15:00', entregas: 52, insucesso: 5 },
  { hora: '16:00', entregas: 48, insucesso: 4 },
  { hora: '17:00', entregas: 35, insucesso: 2 },
  { hora: '18:00', entregas: 18, insucesso: 1 },
];

// Status distribution data
export const statusDistributionData = [
  { status: 'Entregue', quantidade: 89, fill: 'var(--chart-1)' },
  { status: 'Em Transito', quantidade: 42, fill: 'var(--chart-2)' },
  { status: 'Pendente', quantidade: 18, fill: 'var(--chart-3)' },
  { status: 'Insucesso', quantidade: 7, fill: 'var(--chart-4)' },
];
